version: '3.8'
services:
    #################################################################
    #                      portainer:
    #################################################################
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:${PORTAINER_VERSION}
    command: -H unix:///var/run/docker.sock
    restart: unless-stopped
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA}/docker/portainer:/data
    #################################################################
    #                      watchtower:
    #################################################################
  watchtower:
    container_name: watchtower
    restart: unless-stopped
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 4 * * *" --cleanup
